# Try it yourself
Find another dataset for binary classification from Kaggle or take a look at sklearn‘s breast cancer dataset. Use sklearn to build your own Logistic Regression model on the data and make some predictions. Which features are most important in the model you build?

In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score


In [56]:
# load the data
data = load_breast_cancer()
data.target[0]

0

In [57]:
# standardise the data
scalar = StandardScaler()
scalar.fit(data.data)
X=scalar.transform(data.data)
print(X.shape)
y=data.target
print(y.shape)

(569, 30)
(569,)


In [58]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=80)

In [74]:
X_train

array([[1.287e+01, 1.621e+01, 8.238e+01, ..., 5.780e-02, 3.604e-01,
        7.062e-02],
       [1.785e+01, 1.323e+01, 1.146e+02, ..., 8.341e-02, 1.783e-01,
        5.871e-02],
       [2.018e+01, 1.954e+01, 1.338e+02, ..., 2.173e-01, 3.032e-01,
        8.075e-02],
       ...,
       [1.184e+01, 1.894e+01, 7.551e+01, ..., 6.913e-02, 2.535e-01,
        7.993e-02],
       [1.181e+01, 1.739e+01, 7.527e+01, ..., 4.306e-02, 3.200e-01,
        6.576e-02],
       [8.671e+00, 1.445e+01, 5.442e+01, ..., 0.000e+00, 2.592e-01,
        7.848e-02]])

In [59]:
# create a logistic regression model
cc_lr = LogisticRegression()
cc_lr.fit(X_train,y_train)
y_pred =cc_lr.predict(X_test)

In [60]:
# Look at the scoring
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)
# True negative = 41
# True Positive = 69
# False negative = 1
# False positive = 3

array([[41,  3],
       [ 1, 69]], dtype=int64)

In [61]:
# Print accuracy here:
print(accuracy_score(y_test, y_pred))

# Print F1 score here:
print(f1_score(y_test, y_pred))

0.9649122807017544
0.971830985915493


## Now without standardisation

In [70]:
X=data.data
print(X.shape)
y=data.target
print(y.shape)

(569, 30)
(569,)


In [71]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=80)

In [73]:
X_train

array([[1.287e+01, 1.621e+01, 8.238e+01, ..., 5.780e-02, 3.604e-01,
        7.062e-02],
       [1.785e+01, 1.323e+01, 1.146e+02, ..., 8.341e-02, 1.783e-01,
        5.871e-02],
       [2.018e+01, 1.954e+01, 1.338e+02, ..., 2.173e-01, 3.032e-01,
        8.075e-02],
       ...,
       [1.184e+01, 1.894e+01, 7.551e+01, ..., 6.913e-02, 2.535e-01,
        7.993e-02],
       [1.181e+01, 1.739e+01, 7.527e+01, ..., 4.306e-02, 3.200e-01,
        6.576e-02],
       [8.671e+00, 1.445e+01, 5.442e+01, ..., 0.000e+00, 2.592e-01,
        7.848e-02]])

In [72]:
# create a logistic regression model
cc_lr2 = LogisticRegression()
cc_lr2.fit(X_train, y_train)
y_pred =cc_lr2.predict(X_test)

AttributeError: 'str' object has no attribute 'decode'